### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [PimvanderLoos/AnimatedArchitecture#344]
https://hosted.weblate.org/projects/AnimatedArchitecture/#information
says CC0, but that creates a bunch of problems, since public domain laws are not compatible across jurisdictions, or even available in this manner. It thus becomes very problematic to even tell what the effective licensing is for anything that can be considered "a work", made harder still for every person contributing to it.

For collaborative work, this is a problem created, with no problems solved.

GPLv3-or-later would be much better, and is compatible with the source code license.

It can be changed in https://hosted.weblate.org/settings/AnimatedArchitecture/animatedarchitecture-core/
and so on for each component.

**Comment by PimvanderLoos** [comment]
Thank you very much for your message!

I was not aware of the issues with CC0. I figured it would make it easier for contributors to go with a less restrictive license, but I guess not.

I have now updated the license to GPLv3+.

However, I've also locked the project for the time being, as I plan on making some changes to the localization setup to make use of the new features I recently added to the Text system and I don't want to waste anyone's time on stuff that will be replaced.
