### ISSUE TITLE
Missing Space in Description in every "New Door Creation Button" in Main Menu

### ISSUE THREAD

**Issue by Chris6ix** [PimvanderLoos/AnimatedArchitecture#45]
![2022-01-22_17 44 40](https://user-images.githubusercontent.com/65610536/150649235-4e5c55d0-68ef-4925-9e3d-cf73c22ff5ec.png)

**Comment by PimvanderLoos** [comment]
Thanks for the report! It's been updated!

**Comment by Chris6ix** [comment]
No problem :)
