### ISSUE TITLE
Not-a-bug I'm stupid dev please help me rotate a log

### ISSUE THREAD

**Issue by BorealPawPads** [PimvanderLoos/AnimatedArchitecture#451]
![2023-04-23_18 09 37](https://user-images.githubusercontent.com/127386236/235091672-367e7375-3b95-4f5a-be87-a1a5297effeb.png)

My friend and I have built this really cool windmill. But we couldn't figure out how to get the beam/log in the center of it, the thing the blades are on, to also spin.

I tried using a clock, another windmill... Rotating door. Is there a way to do this? If not, I'd like to request this feature!

**Comment by PimvanderLoos** [comment]
Hey, this is a known bug with all rotating structure types. The blocks at the rotation point will not spin by themselves. It will be fixed in a future update.

**Comment by BorealPawPads** [comment]
Excellent. Many thanks again for this AMAZING plugin. Hopefully these bug reports aren't getting spammy!

**Comment by PimvanderLoos** [comment]
Hey, these bug reports aren't spammy at all! It's actually really nice to know that people are actually using it, and it's even better to know what I should focus on to improve this project, so the more the better!

I'm just sorry it's taking longer to push out fixes than I'd like, but I've just been very busy. Having said that, I hope to find some time to work on a fix for this issue tomorrow. Fixes for the other issues should be out now :)
