### ISSUE TITLE
Please give more than 60 seconds to create a new structure

### ISSUE THREAD

**Issue by BorealPawPads** [PimvanderLoos/AnimatedArchitecture#452]
Hello again!

I'd like to request more than 60 seconds to complete all the steps related to creating a new structure. Since it has to be done in survival (it doesn't work in creative, maybe that's a separate bug), if it's a large structure there's not enough time to get from points A to B to C. Alternatively, maybe get rid of the time limit altogether and just rely on manually cancelling on failure?

**Comment by PimvanderLoos** [comment]
That is actually an error in the localized message. While it says 60 seconds [there](https://github.com/PimvanderLoos/AnimatedArchitecture/blob/fea8f0706d2c690ee1c3488947b109a7510b7c8d/animatedarchitecture-core/src/main/resources/Core.properties#L73), it's actually [3 minutes](https://github.com/PimvanderLoos/AnimatedArchitecture/blob/fea8f0706d2c690ee1c3488947b109a7510b7c8d/animatedarchitecture-core/src/main/java/nl/pim16aap2/animatedarchitecture/core/util/Constants.java#L63) (used [here](https://github.com/PimvanderLoos/AnimatedArchitecture/blob/fea8f0706d2c690ee1c3488947b109a7510b7c8d/animatedarchitecture-core/src/main/java/nl/pim16aap2/animatedarchitecture/core/commands/NewStructure.java#L69-L71)).

The reason for timing out is that I don't like leaving the process waiting for input until the server shuts down in case a player gets distracted or something. However, even 3 minutes might be a little too tight. I'll update it to 15 minutes or so.

And the creator process should work in creative mode as well. I was not aware of any issues with it. I'll have to look into that.
