### ISSUE TITLE
Plugin AnimatedArchitecture v0.4 generated an exception while executing task

### ISSUE THREAD

**Issue by BorealPawPads** [PimvanderLoos/AnimatedArchitecture#459]
[15:06:20 WARN]: [AnimatedArchitecture] Plugin AnimatedArchitecture v0.4 generated an exception while executing task 3386
java.lang.AbstractMethodError: Receiver class nl.pim16aap2.animatedarchitecture.structures.windmill.WindmillAnimationComponent does not define or inherit an implementatio
n of the resolved method 'abstract void executeAnimationStep(nl.pim16aap2.animatedarchitecture.core.animation.IAnimator, java.lang.Iterable, int)' of interface nl.pim16aa
p2.animatedarchitecture.core.animation.IAnimationComponent.                                                                                                                       at nl.pim16aap2.animatedarchitecture.core.animation.Animator.executeAnimationStep(Animator.java:332) ~[AnimatedArchitecture-Spigot.jar:?]                                 at nl.pim16aap2.animatedarchitecture.core.animation.Animator$1.run(Animator.java:469) ~[AnimatedArchitecture-Spigot.jar:?]
        at nl.pim16aap2.animatedarchitecture.spigot.util.implementations.ExecutorSpigot$1.run(ExecutorSpigot.java:170) ~[AnimatedArchitecture-Spigot.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-513]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-513]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by BorealPawPads** [comment]
This repeats on spigot/paper sever start until I kil the process.

**Comment by PimvanderLoos** [comment]
Oh, that's annoying. I'll work on a fix.

Thanks for the heads-up!

**Comment by PimvanderLoos** [comment]
I cannot replicate this issue.

Did you also update the structure jars in the extensions folder? I made some changes to 0.4 when reworking the local rotation calculations that updated the internal APIs used for the animation components. As such, the extensions will have to be updated as well.

Ideally, the plugin should catch this and inform you, but I'm not entirely sure what the best way to approach that would be.

**Comment by BorealPawPads** [comment]
I forgot the structures in the extensions folder.

WHOOPSIDOODLE.

It works now...

**Comment by PimvanderLoos** [comment]
Ah, I'm glad to hear it!

I was already wondering whether to just scrap the whole system where each type of structure is its own jar. I guess this is one more point in favor of doing so :)
In theory, it's nice, as it allows you to quickly and easily create and install new types of structures, but I don't really see other people making custom types at this point, so it'd just be easier for everyone to package them into the main jar.

**Comment by BorealPawPads** [comment]
> Ah, I'm glad to hear it!
> 
> I was already wondering whether to just scrap the whole system where each type of structure is its own jar. I guess this is one more point in favor of doing so :) In theory, it's nice, as it allows you to quickly and easily create and install new types of structures, but I don't really see other people making custom types at this point, so it'd just be easier for everyone to package them into the main jar.

I think this would be doable by having the "core" structures built into the main jar, but leave an option open for people to add custom ones at a later point, just in case!
