### ISSUE TITLE
Blocks from deleted structures cannot be removed from the world

### ISSUE THREAD

**Issue by BorealPawPads** [PimvanderLoos/AnimatedArchitecture#461]
Hello there!

It seems something happened when a windmill structure was deleted while still spinning.

Now the blocks are stuck mid-animation and you can't get rid of them, even in creative!

How can I get rid of these stuck blocks?

![2023-05-07_12 09 48](https://user-images.githubusercontent.com/127386236/236671391-d4c1827d-7532-461e-8046-106c3224c720.png)

**Comment by PimvanderLoos** [comment]
I'll work on a fix to ensure this won't happen again!

To remove them, you can use Minecraft's kill command: `/kill @e[type=minecraft:block_display,distance=25]`. You can adjust the distance if needed. This will simply remove the blocks, so I'm afraid you will not get the old windmill back in place :(

**Comment by BorealPawPads** [comment]
> I'll work on a fix to ensure this won't happen again!
> 
> To remove them, you can use Minecraft's kill command: `/kill @e[type=minecraft:block_display,distance=25]`. You can adjust the distance if needed. This will simply remove the blocks, so I'm afraid you will not get the old windmill back in place :(

No entity was found!

**Comment by PimvanderLoos** [comment]
Oh, my bad, it looks like I messed up the syntax. The correct command is actually `/minecraft:kill @e[type=minecraft:block_display,distance=..25]` to kill all block displays (the animated blocks used by this plugin) within 25 blocks.

**Comment by BorealPawPads** [comment]
Thanks so much for all the quick and personal support! As they would say on eBay reviews, A+++ developer!
