### ISSUE TITLE
Structures don't work if the owner of them isn't online

### ISSUE THREAD

**Issue by CammiePone** [PimvanderLoos/AnimatedArchitecture#557]
A friend figured this out for me, and I confirmed using my alt account. Apparently structures will not work unless the owner of the structure is online, resulting in things like doors remaining permanently closed and flags and windmills stopping.

**Comment by CammiePone** [comment]
It seems the owner of the structure has to have been logged off for an extended period of time, so it works at least for a few minutes after the owner logs off.

**Comment by CammiePone** [comment]
Constantly powered structures also stop on server reload.

**Comment by PimvanderLoos** [comment]
Which protection plugins are you hooked into and is AA able to create fake players?
You can find this information under the `ProtectionHookManagerSpigot` section of the output of the `AnimatedArchitecture debug` command.

And which version of AA are you on? If it's a snapshot, could you provide the build data as well? You can find that under the `BuildDataReader` section of the debug dump.

If you cannot find these sections, you can also just post the debug output here.

**Comment by CammiePone** [comment]
of course! good to know that command exists. I come from modding where useful stuff like this isn't super common
```
nl.pim16aap2.animatedarchitecture.spigot.core.hooks.ProtectionHookManagerSpigot:
  Can create fake players: true
  Protection hooks: 
    Towny
```
```
nl.pim16aap2.animatedarchitecture.core.util.versioning.BuildDataReader:
  Commit: master: 5751fb522342dd52224c1e90d4382c37e4dc4bb2 dirty:false (2023-08-03T09:28:17+0000)
  Build number: -1
  Build id: -1
```

**Comment by CammiePone** [comment]
okay this is a bit strange. I know this wasn't working yesterday and the day before, but suddenly they're working again? I tried to see if maybe it was because of a server restart, but even then they still worked just fine on a different account. I'm wondering if it might have something to do with /reload but i'll have to test that later

**Comment by CammiePone** [comment]
yup just got a friend to confirm it for me, it's suddenly working again? I have no idea and now im super confused. though the flag and windmill did stop after /reload, but given that isn't supposed to be used with any frequency, it's not as big an issue as initially thought

**Comment by rainbowdashlabs** [comment]
Reloading is in general something you should never do. Nearly all Devs do not support reloading the server. There are countless reasons why you shouldn't do this.
https://madelinemiller.dev/blog/problem-with-reload/

**Comment by PimvanderLoos** [comment]
Yeah, I'd recommend to avoid using the reload command.
If you want to reload/restart AA, you can use the `/AnimatedArchitecture restart` command and the plugin will reinitialize itself.

Does avoiding the reload command also fix the original issue with structures not working if the original creator is offline?

**Comment by PimvanderLoos** [comment]
A lot has changed for the protection hooks, so I'm just going to go ahead and close this issue. If this still happens on more recent builds, please let me know.
