### ISSUE TITLE
[Feature request] A option to use blocks instead of display entities

### ISSUE THREAD

**Issue by ghost** [PimvanderLoos/AnimatedArchitecture#805]
While better than armorstands pre 1.19.4, display entities still require a price of performance on the client. For lesser able systems this might prove taxing.

A option to use standard blocks instead of display entities would be a great option to have, it would make the animation less smooth due to having less places. But it would allow for players with older machines to handle them much better.

**Comment by PimvanderLoos** [comment]
I currently have no plans for a feature like this. I might add a feature to disable animated blocks per-player, but I'm not sure when/how/if I will implement that.
