### ISSUE TITLE
the doors can be opened with arrows by players who do not own the door

### ISSUE THREAD

**Issue by haroldrc** [PimvanderLoos/AnimatedArchitecture#97]

**Comment by PimvanderLoos** [comment]
I'm not entirely sure what you mean.

The only way I can think of that allows anyone (owner of a door or not) to open a door with an arrow would be by shooting a button connected to a powerblock either directly or via a redstone signal. 
This is intended behavior, as the plugin does not trace who causes a redstone signal to be activated, as this would get extremely complicated and expensive very quickly for redstone mechanisms. While it's, of course, easy and cheap to do when it's a button directly attached to a powerblock, I don't want there to be a difference in redstone functionality depending on _how_ you wire it up, as this would just be too confusing.
